#!/usr/bin/env python3
"""Record reference pixel_values for HuggingFaceTransformers.jl's image processor
parity test.

Usage:
    python3 test/fixtures/record_image_processor_parity.py

Requirements:
    pip install transformers torch torchvision pillow
    # HF's default image processors run on torchvision; that is the path
    # recorded here.

No model is downloaded. Each case is a small `preprocessor_config.json`, loaded
through `AutoImageProcessor` exactly as a checkpoint's would be, and applied to an
image generated by `image_pattern` (mirrored in test/parity_inputs.jl). Configs
leave some keys out on purpose, so the class defaults are part of what is tested.

Outputs are kept small (16-20 pixels a side) and stored as base64 float32, which
is both compact and exact: the Julia side compares at 1e-6, well below the
1/255/std gap between neighbouring byte values, so a resize off by a single level
fails.
"""
import base64
import json
import os
import sys
import tempfile

import numpy as np
from transformers import AutoImageProcessor

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from parity_inputs import image_pattern  # noqa: E402

FIXTURES_DIR = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(FIXTURES_DIR, "image_processor_parity.json")

CASES = [
    # ViT's real config names no class and gives a bare integer size; this
    # older spelling exercises the FeatureExtractor -> ImageProcessor rename.
    ("vit_legacy_bilinear", 67, 91, "uint8",
     {"feature_extractor_type": "ViTFeatureExtractor", "size": 16}),
    ("siglip_bicubic_nonsquare", 67, 91, "uint8",
     {"image_processor_type": "SiglipImageProcessor", "size": {"height": 16, "width": 20}}),
    # DINOv2's recipe: shortest edge, then center crop, ImageNet statistics.
    ("bit_shortest_edge_crop", 67, 91, "uint8",
     {"image_processor_type": "BitImageProcessor", "size": {"shortest_edge": 20},
      "crop_size": {"height": 16, "width": 16},
      "image_mean": [0.485, 0.456, 0.406], "image_std": [0.229, 0.224, 0.225]}),
    # Upscaling a portrait image: the shortest edge is the width, and bicubic
    # overshoot past 0 and 255 has to clip.
    ("clip_upscale_portrait", 13, 11, "uint8",
     {"image_processor_type": "CLIPImageProcessorFast", "size": {"shortest_edge": 20},
      "crop_size": 16}),
    ("bit_crop_pads", 13, 11, "uint8",
     {"image_processor_type": "BitImageProcessor", "do_resize": False,
      "crop_size": {"height": 16, "width": 12}}),
    ("siglip_rescale_only", 67, 91, "uint8",
     {"image_processor_type": "SiglipImageProcessor", "size": {"height": 16, "width": 16},
      "do_normalize": False}),
    # Float input is resized in float32, with no rounding between passes.
    ("vit_float_bicubic", 67, 91, "float32",
     {"image_processor_type": "ViTImageProcessor", "size": {"height": 16, "width": 16},
      "resample": 3}),
]


def main():
    cases = []
    for name, height, width, dtype, config in CASES:
        with tempfile.TemporaryDirectory() as tmp:
            with open(os.path.join(tmp, "preprocessor_config.json"), "w") as f:
                json.dump(config, f)
            processor = AutoImageProcessor.from_pretrained(tmp)
        image = image_pattern(height, width).astype(dtype)
        pixels = processor(images=image, input_data_format="channels_last",
                           return_tensors="np").pixel_values[0]
        pixels = np.ascontiguousarray(pixels, dtype="<f4")
        cases.append({
            "name": name,
            "processor": type(processor).__name__,
            "config": config,
            "height": height,
            "width": width,
            "dtype": dtype,
            # (C, H, W), row-major.
            "shape": list(pixels.shape),
            "pixel_values": base64.b64encode(pixels.tobytes()).decode("ascii"),
            "tolerance": 1e-6 if dtype == "uint8" else 1e-4,
        })
        print(f"{name}: {type(processor).__name__} -> {pixels.shape}")
    with open(OUT, "w") as f:
        json.dump({"cases": cases}, f, separators=(",", ":"))
    print(f"Wrote {OUT} ({os.path.getsize(OUT) // 1024} KB)")


if __name__ == "__main__":
    main()
